apiVersion: route.openshift.io/v1
kind: Route
metadata: 
  labels: 
    app.kubernetes.io/instance: import-tests-go-gepmfrii-import
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: import-tests-go-gepmfrii-import 
  name: import-tests-go-gepmfrii-import
spec:
  port:
    targetPort: 8081 
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: import-tests-go-gepmfrii-import
    weight: 100 
